### ISSUE TITLE
issue when running v2.3.0

### ISSUE THREAD

**Issue by techmsi** [kiwigrid/gherkin-testcafe#36]
## Versions
mac v.10.13.6
node v10.15.3

I believe there may a package versioning mismatch.

v2.2.0 works without an error.

## Error
```
ERROR TypeError: ExeFile is not a constructor
    at new Gherkin (myproject/node_modules/gherkin-testcafe/node_modules/gherkin/dist/src/index.js:48:21)
    at Object.fromPaths (myproject/node_modules/gherkin-testcafe/node_modules/gherkin/dist/src/index.js:18:10)
    at Promise.all.specFiles.map (myproject/node_modules/gherkin-testcafe/src/compiler.js:65:65)
    at Array.map (<anonymous>)
    at GherkinTestcafeCompiler.getTests (myproject/node_modules/gherkin-testcafe/src/compiler.js:64:22)
    at Bootstrapper._getTests (myproject/node_modules/testcafe/src/runner/bootstrapper.js:79:47)
```

**Comment by Lukas-Kullmann** [comment]
Hi @techmsi,

I cannot reproduce your error. But you might be right, that the the package `c21e` is installed in version 1.1.9 or something similar?

Just run `npm ls c21e`. You should see something like this:

```
gherkin-testcafe@2.3.0
└─┬ gherkin@6.0.17
  └── c21e@1.1.9 
```

If not, please make sure that the package is installed correctly. Maybe you can to dedupe your packages with `npm dedupe`. This solved quite some problems of mine in the past.

**Comment by troianoandres** [comment]
Hi, I'm seeing exactly the same issue, the `c21e` version that it is being installed is `1.2.1`. I will try to install `1.1.9` to check if that fixes the issue. Any toughts?

**Comment by troianoandres** [comment]
Hi again, I've just checked that the issue is regarding the versions of `c21e`. Seems that their minor change is actually not minor. Also, since it is part of the `gherkin` package we are not able to lock it up.

**Comment by Lukas-Kullmann** [comment]
Thanks for trying this out, @troianoandres!

I opened an issue at cucumber's and hope they will fix the problem on their side.

**Comment by eddiegroves** [comment]
For reference, I've worked around this for now by using Yarn's selective version resolutions:

https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by leegee** [comment]
Seeing the same here, will try the suggested work around.

```
Lees-MacBook-Pro:app lee$ gherkin-testcafe firefox e2e/listings.js e2e/listings.feature
ERROR TypeError: ExeFile is not a constructor
    at new Gherkin (/Users/lee/src/zpg/app-lsrp/app/node_modules/gherkin-testcafe/node_modules/gherkin/dist/src/index.js:48:21)
    at Object.fromPaths (/Users/lee/src/zpg/app-lsrp/app/node_modules/gherkin-testcafe/node_modules/gherkin/dist/src/index.js:18:10)
    at /Users/lee/src/zpg/app-lsrp/app/node_modules/gherkin-testcafe/src/compiler.js:65:65
    at Array.map (<anonymous>)
    at GherkinTestcafeCompiler.getTests (/Users/lee/src/zpg/app-lsrp/app/node_modules/gherkin-testcafe/src/compiler.js:64:22)
    at Bootstrapper._getTests (/Users/lee/src/zpg/app-lsrp/app/node_modules/testcafe/src/runner/bootstrapper.js:79:47)
```

**Comment by leegee** [comment]
Make c21e@1.1.9 a dep of my project worked.
