### ISSUE TITLE
internal/modules/cjs/loader.js:984   throw err; Error: Cannot find module 'indent-string'

### ISSUE THREAD

**Issue by ktryniszewski-mdsol** [kiwigrid/gherkin-testcafe#59]
Kind of new to npm in general, but installed the modules as stated but trying to run gherkin-testcafe throws this error

internal/modules/cjs/loader.js:984
  throw err;
  ^

Error: Cannot find module 'indent-string'
Require stack:
- /usr/local/lib/node_modules/cucumber/lib/formatter/helpers/issue_helpers.js
- /usr/local/lib/node_modules/cucumber/lib/formatter/helpers/index.js
- /usr/local/lib/node_modules/cucumber/lib/index.js
- /usr/local/lib/node_modules/gherkin-testcafe/src/compiler.js
- /usr/local/lib/node_modules/gherkin-testcafe/src/rewire-compiler.js
- /usr/local/lib/node_modules/gherkin-testcafe/src/cli.js
- /usr/local/lib/node_modules/gherkin-testcafe/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/cucumber/lib/formatter/helpers/issue_helpers.js:13:44)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/cucumber/lib/formatter/helpers/index.js:96:22)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/cucumber/lib/formatter/helpers/issue_helpers.js',
    '/usr/local/lib/node_modules/cucumber/lib/formatter/helpers/index.js',
    '/usr/local/lib/node_modules/cucumber/lib/index.js',
    '/usr/local/lib/node_modules/gherkin-testcafe/src/compiler.js',
    '/usr/local/lib/node_modules/gherkin-testcafe/src/rewire-compiler.js',
    '/usr/local/lib/node_modules/gherkin-testcafe/src/cli.js',
    '/usr/local/lib/node_modules/gherkin-testcafe/main.js'
  ]
}

tried reinstalling node and what not but same issue
even tried downgrading cucumber to 5.1.0 as that is specified in your package.json

Any help would be greatly appreciated

**Comment by eddiegroves** [comment]
Looks like you're trying to use this with global installs of the npm modules. In general, you create a project and install all of your npm modules inside that folder, so that all dependencies are contained within that project's node_modules.

Try this:

```
mkdir my-tests
cd my-tests
npm init
npm install gherkin-testcafe cucumber testcafe
```

You will now have, inside `my-tests`:

```
node_modules
package-lock.json
package.json
```

The `node_modules` folder should now contain everything that project needs, including that pesky `indent-string`.

If you're used to package managers all sharing the same files etc globally, it is a bit strange but as they say, "when in Rome"...

**Comment by ktryniszewski-mdsol** [comment]
interesting, yea originally i installed everything but ```gherkin-testcafe``` command wasnt found so I had to ```npm link``` it
but then i would get the above error

found that globally installing cucumber fixed it

however later i learned that using ```npx gherkin-testcafe``` works without having to install anything globally.
